notifications:
  email: false
  slack:
    rooms:
      secure: PxuIjhULoC8GEyoYWTZQwIzEori+7/N5NLTJcY01TkqjQVdIjxdf33Py6ky9DgIxWOrG0R5jIrQ8eD9Coee34s/av85HDFwJMwY2UTTtYcYUdDUIo6g1OmAGYGAcnyZxUsYknK51sh1w6C4YSjlkuKYNpryse8pSHzE26qOirONGwccPXcN9AZHHonWKRYq0mjaseMgVmp4rGQufMksP80LLt1stzDsShFvVRo5zO1gvmmK5IDUqSocPTfNYThsvqS6Wdp+a9O/uDmx3coNDgkqPm1Fj58Q1Bklmi+gEm2cHCQgOGa1bYN+EivLw+4oFGuq6Yz1qKaF3fivE/jUDgqmOx2cYpyUXUtcqvjezIx/EOjvf8heC5xZZ2NUE0RCNPr8RzGzltWwZLU09Td1PxXZlQ6II6r1kKHLLfzi4Uf7von159FK4L7+/rae3V1T7qI1Rif6sHV1uD4wdleaJVtqM1p4UUWiV7jHdRJke5C0MhM1+PUfiHJTDszm2Iv8Fkac+TM5Yya1p87/t+jgfBRlZ1i+wuJiec4EU3Ch9o9J+ptKnAhwKzvM4xab95mm6OOQ4cZaedOWLJuKTCpZ2KJJA73x0lPDUNYELXsDMB13DYbqkE7R2/XOW0oIQ+BCcviKGEqInjogjYlvrJ4y8HtOsV1vmzbCWjNGFWM2RurY=
    on_success: always
    on_failure: always

stages:
- name: APP
  if: commit_message !~ /(skip[ _-]app)/

jobs:
  include:
    
  - stage: APP
    os: linux
    language: node_js
    node_js:
    - '12.16'
    services:
    - docker
    before_script:
    - export -f travis_fold
    script:
    - bash .travis.app.sh

  - stage: DOC
    language: node_js
    node_js:
    - '12.16'
    install: true
    script: bash .travis.doc.sh
    deploy:
      provider: pages
      local-dir: docs/.vuepress/dist
      skip-cleanup: true
      github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep-history: true
      on:
        branch: master      